_merge: deep
theme: osuny
enableRobotsTXT: true
removePathAccents: true
params:
  keycdn:
    url: https://osunystaging-1b4da.kxcdn.com
  summary:
    position: hero
  search:
    active: false
  single:
    navigation:
      active: false
